In [1]:
import pandas as analytics
import numpy as maths
import os

In [5]:
def extract_values(a):
    return [i.strip().replace(" ","_") for i in a.split("|")]

In [2]:
source_path = 'MovieLens100k_dataset'
data_path = os.path.join(source_path,'u.data')
genre_path = os.path.join(source_path,'u.genre')
item_path = os.path.join(source_path,'u.item')
occupation_path = os.path.join(source_path,'u.occupation')
user_path = os.path.join(source_path,'u.user')


In [3]:
df_rated_movies = analytics.read_csv('rated_movies.csv')
user_id = df_rated_movies['user_id'].unique()[0]
df_rated_movies = df_rated_movies.drop(['user_id','timestamp'],axis = 1)
df_rated_movies

movie_id                movie_title  rating  Action  Adventure  \
0           1           Toy Story (1995)       1       0          0   
1           2           GoldenEye (1995)       1       1          1   
2           3          Four Rooms (1995)       1       0          0   
3           4          Get Shorty (1995)       0       1          0   
4           7      Twelve Monkeys (1995)       1       0          0   
..        ...                        ...     ...     ...        ...   
535      1480  Herbie Rides Again (1974)       0       0          1   
536      1490              Fausto (1993)       0       0          0   
537      1518       Losing Isaiah (1995)       1       0          0   
538      1521       Mr. Wonderful (1993)       0       0          0   
539      1603              Angela (1995)       0       0          0   

     Animation  Children's  Comedy  Crime  Documentary  ...  Fantasy  \
0            1           1       1      0            0  ...        0   
1            0           0       0      0            0  ...        0   
2            0           0       0      0            0  ...        0   
3            0           0       1      0            0  ...        0   
4            0           0       0      0            0  ...        0   
..         ...         ...     ...    ...          ...  ...      ...   
535          0           1       1      0            0  ...        0   
536          0           0       1      0            0  ...        0   
537          0           0       0      0            0  ...        0   
538          0           0       1      0            0  ...        0   
539          0           0       0      0            0  ...        0   

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0            0       0        0        0        0       0         0    0   
1            0       0        0        0        0       0         1    0   
2            0       0        0        0        0       0         1    0   
3            0       0        0        0        0       0         0    0   
4            0       0        0        0        0       1         0    0   
..         ...     ...      ...      ...      ...     ...       ...  ...   
535          0       0        0        0        0       0         0    0   
536          0       0        0        0        0       0         0    0   
537          0       0        0        0        0       0         0    0   
538          0       0        0        0        1       0         0    0   
539          0       0        0        0        0       0         0    0   

     Western  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
535        0  
536        0  
537        0  
538        0  
539        0  

[540 rows x 21 columns]

In [6]:
data_headers = """user id | movie id | rating | timestamp"""
item_headers = """movie id | movie title | release date | video release date |
              IMDb URL | unknown | Action | Adventure | Animation |
              Children's | Comedy | Crime | Documentary | Drama | Fantasy |
              Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi |
              Thriller | War | Western |"""
user_headers = """user id | age | gender | occupation | zip code"""


data_headers = extract_values(data_headers)
item_headers = extract_values(item_headers)[:-1]
user_headers = extract_values(user_headers)
genres = analytics.read_csv(genre_path,sep="|")['unknown'].tolist()

In [7]:
df_data = analytics.read_csv(data_path,header = None,sep="\t",names = data_headers)
df_data['rating'] = df_data['rating'] - 3
df_data

user_id  movie_id  rating  timestamp
0          196       242       0  881250949
1          186       302       0  891717742
2           22       377      -2  878887116
3          244        51      -1  880606923
4          166       346      -2  886397596
...        ...       ...     ...        ...
99995      880       476       0  880175444
99996      716       204       2  879795543
99997      276      1090      -2  874795795
99998       13       225      -1  882399156
99999       12       203       0  879959583

[100000 rows x 4 columns]

In [8]:
df_items = analytics.read_csv(item_path, header = None, sep = "|" , names = item_headers)
df_items = df_items.drop(['release_date','video_release_date','IMDb_URL'],axis = 1)
df_items = df_items[df_items['unknown'] == 0]
df_items = df_items.drop('unknown',axis = 1)
df_items

movie_id                                movie_title  Action  Adventure  \
0            1                           Toy Story (1995)       0          0   
1            2                           GoldenEye (1995)       1          1   
2            3                          Four Rooms (1995)       0          0   
3            4                          Get Shorty (1995)       1          0   
4            5                             Copycat (1995)       0          0   
...        ...                                        ...     ...        ...   
1676      1678                          Mat' i syn (1997)       0          0   
1677      1679                           B. Monkey (1998)       0          0   
1678      1680                       Sliding Doors (1998)       0          0   
1679      1681                        You So Crazy (1994)       0          0   
1680      1682  Scream of Stone (Schrei aus Stein) (1991)       0          0   

      Animation  Children's  Comedy  Crime  Documentary  Drama  Fantasy  \
0             1           1       1      0            0      0        0   
1             0           0       0      0            0      0        0   
2             0           0       0      0            0      0        0   
3             0           0       1      0            0      1        0   
4             0           0       0      1            0      1        0   
...         ...         ...     ...    ...          ...    ...      ...   
1676          0           0       0      0            0      1        0   
1677          0           0       0      0            0      0        0   
1678          0           0       0      0            0      1        0   
1679          0           0       1      0            0      0        0   
1680          0           0       0      0            0      1        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1676          0       0        0        0        0       0         0    0   
1677          0       0        0        0        1       0         1    0   
1678          0       0        0        0        1       0         0    0   
1679          0       0        0        0        0       0         0    0   
1680          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1676        0  
1677        0  
1678        0  
1679        0  
1680        0  

[1679 rows x 20 columns]

In [37]:
df_maps = df_data.groupby('user_id').agg({'movie_id':lambda x:x.count(),'rating':lambda x:x.sum()}).reset_index()
df_maps['arpm'] = df_maps['rating']/df_maps['movie_id']
df_maps = df_maps[df_maps['movie_id'] > 149]
most_liberal_user = df_maps.set_index('user_id')['arpm'].argmax()

In [111]:
df_liberal = df_data[df_data['user_id'] == most_liberal_user].reset_index(drop = True).sort_values('timestamp')
df_liberal

user_id  movie_id  rating  timestamp
14       77       181       0  884732278
18       77        50       1  884732345
3        77       474       2  884732407
69       77       183       2  884732606
12       77       153       2  884732685
..      ...       ...     ...        ...
1        77       518       1  884753202
28       77       778      -1  884753203
26       77        52       2  884753203
36       77        97      -1  884753292
49       77        31       0  884753292

[72 rows x 4 columns]

In [112]:
df_liberal = df_liberal.merge(df_items,on='movie_id')
df_train = df_liberal.sample(frac = 0.8)
df_test = df_liberal[~df_liberal.isin(df_train)].dropna()
df_liberal

user_id  movie_id  rating  timestamp  \
0        77       181       0  884732278   
1        77        50       1  884732345   
2        77       474       2  884732407   
3        77       183       2  884732606   
4        77       153       2  884732685   
..      ...       ...     ...        ...   
67       77       518       1  884753202   
68       77       778      -1  884753203   
69       77        52       2  884753203   
70       77        97      -1  884753292   
71       77        31       0  884753292   

                                          movie_title  Action  Adventure  \
0                           Return of the Jedi (1983)       1          1   
1                                    Star Wars (1977)       1          1   
2   Dr. Strangelove or: How I Learned to Stop Worr...       0          0   
3                                        Alien (1979)       1          0   
4                         Fish Called Wanda, A (1988)       0          0   
..                                                ...     ...        ...   
67                           Miller's Crossing (1990)       0          0   
68                            Don Juan DeMarco (1995)       0          0   
69                 Madness of King George, The (1994)       0          0   
70                          Dances with Wolves (1990)       0          1   
71                                Crimson Tide (1995)       0          0   

    Animation  Children's  Comedy  ...  Fantasy  Film-Noir  Horror  Musical  \
0           0           0       0  ...        0          0       0        0   
1           0           0       0  ...        0          0       0        0   
2           0           0       0  ...        0          0       0        0   
3           0           0       0  ...        0          0       1        0   
4           0           0       1  ...        0          0       0        0   
..        ...         ...     ...  ...      ...        ...     ...      ...   
67          0           0       0  ...        0          0       0        0   
68          0           0       1  ...        0          0       0        0   
69          0           0       0  ...        0          0       0        0   
70          0           0       0  ...        0          0       0        0   
71          0           0       0  ...        0          0       0        0   

    Mystery  Romance  Sci-Fi  Thriller  War  Western  
0         0        1       1         0    1        0  
1         0        1       1         0    1        0  
2         0        0       1         0    1        0  
3         0        0       1         1    0        0  
4         0        0       0         0    0        0  
..      ...      ...     ...       ...  ...      ...  
67        0        0       0         0    0        0  
68        0        1       0         0    0        0  
69        0        0       0         0    0        0  
70        0        0       0         0    0        1  
71        0        0       0         1    1        0  

[72 rows x 23 columns]

In [114]:
len(df_items.columns[2:])

18

In [229]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Embedding, GRU, Dense
from tensorflow.keras.models import Sequential

In [262]:
input_vector.shape[1]

18

In [271]:
embedding_dimension = 20
input_dimension = 18
model = Sequential()
model.add(Embedding(input_dim = input_dimension, output_dim=embedding_dimension))
model.add(GRU(50, activation = 'softmax'))
model.add(Dense(input_dimension, activation='softmax'))
model.compile(loss = 'crossentropy',optimizer='adam', metrics=['recall'])

In [232]:
values = []
rewards = []

In [233]:
t = -1
X = []

In [272]:
X = maths.matrix(df_train[df_train.columns[5:]])[:-1]
y = maths.matrix(df_train[df_train.columns[5:]])[1:]

In [254]:
X[1]

matrix([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [257]:
t = t + 1
input_vector = maths.matrix(df_train[df_train.columns[5:]].iloc[t])
gamma = 0.2
feedback_value = df_train['rating'].iloc[t]
if feedback_value > 0 : value = 1 
else : value = -0.2  
values.append(value*gamma**t)
rewards.append(sum(values[:t]))
embedding_dimension = 20

In [273]:
model.fit(X,y, epochs = 100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.6726 - recall: 0.0000e+00
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6660 - recall: 0.0000e+00
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6590 - recall: 0.0000e+00 
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5017 - recall: 0.0000e+00 
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6731 - recall: 0.0000e+00 
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4868 - recall: 0.0000e+00 
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8061 - recall: 0.0000e+00
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4137 - recall: 0.0000e+00 
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.7929 - recall: 0.0000e+00
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6342 - recall: 0.0000e+00 
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5422 - recall: 0.0000e+00 
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step -

In [277]:
predictions = model.predict(X)
probabilities = maths.exp(predictions) / maths.sum(np.exp(predictions), axis=1, keepdims=True)
probabilities

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[0.05840178, 0.05776998, 0.05362258, ..., 0.05734557, 0.05729209,
        0.0538814 ],
       [0.05840495, 0.05777108, 0.05362144, ..., 0.05734601, 0.05729376,
        0.05387978],
       [0.05830707, 0.05774662, 0.05364542, ..., 0.05737891, 0.05726383,
        0.05391799],
       ...,
       [0.05841069, 0.05777169, 0.05361952, ..., 0.05734542, 0.05729747,
        0.05387657],
       [0.05840346, 0.05776988, 0.05362171, ..., 0.05734618, 0.05729428,
        0.05388029],
       [0.05840666, 0.05777095, 0.0536217 , ..., 0.05734266, 0.05729282,
        0.05387978]], dtype=float32)

In [286]:
probabilities[:,0]

array([0.05840178, 0.05840495, 0.05830707, 0.0584107 , 0.05840369,
       0.05831201, 0.05841072, 0.05839091, 0.05831201, 0.0584055 ,
       0.05840178, 0.0584147 , 0.05821611, 0.05830707, 0.05840346,
       0.05841267, 0.05839625, 0.05841466, 0.05838608, 0.05841092,
       0.05830177, 0.05832484, 0.05840096, 0.05841473, 0.05840732,
       0.05840971, 0.05840001, 0.05840001, 0.05840178, 0.05830707,
       0.05841573, 0.05839651, 0.05829027, 0.05840149, 0.05841568,
       0.05830707, 0.05829027, 0.05840718, 0.058404  , 0.05832484,
       0.05831201, 0.05841032, 0.0584055 , 0.05840422, 0.05830707,
       0.05830707, 0.05840178, 0.05831201, 0.05831201, 0.05839811,
       0.0584107 , 0.05831201, 0.05831201, 0.05840275, 0.05841069,
       0.05840346, 0.05840666], dtype=float32)

In [212]:
rewards

[0,
 1.0,
 1.2,
 1.192,
 1.1904,
 1.192,
 1.19232,
 1.192384,
 1.1923968,
 1.192396288,
 1.1923968,
 1.1923967795200001,
 1.1923967754240001,
 1.1923967746048,
 1.1923967754240001,
 1.1923967753912321,
 1.1923967753846785,
 1.1923967753833677,
 1.1923967753846785,
 1.1923967753849407,
 1.1923967753849303,
 1.1923967753849407]

In [118]:
model.fit(input_vector,rewards[-1])

SyntaxError: incomplete input (2228091118.py, line 1)

In [119]:
embedding = tf.keras.layers.Embedding(input_dim=len(input_vector), output_dim=embedding_dimension)
input_tensor = tf.constant(input_vector)
embedding(input_tensor)

<tf.Tensor: shape=(1, 18, 20), dtype=float32, numpy=
array([[[-0.04157556,  0.00344843, -0.03710697,  0.0420297 ,
          0.02827216,  0.04838764, -0.02540306,  0.01752577,
         -0.03171322, -0.04390177, -0.00579613, -0.0245366 ,
         -0.00652146, -0.00090211, -0.02781671,  0.03336009,
          0.02270869, -0.03565388, -0.02301773, -0.00625051],
        [-0.04157556,  0.00344843, -0.03710697,  0.0420297 ,
          0.02827216,  0.04838764, -0.02540306,  0.01752577,
         -0.03171322, -0.04390177, -0.00579613, -0.0245366 ,
         -0.00652146, -0.00090211, -0.02781671,  0.03336009,
          0.02270869, -0.03565388, -0.02301773, -0.00625051],
        [-0.04157556,  0.00344843, -0.03710697,  0.0420297 ,
          0.02827216,  0.04838764, -0.02540306,  0.01752577,
         -0.03171322, -0.04390177, -0.00579613, -0.0245366 ,
         -0.00652146, -0.00090211, -0.02781671,  0.03336009,
          0.02270869, -0.03565388, -0.02301773, -0.00625051],
        [-0.04157556,  0.0034